// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class Contract
    {
        public Contract()
        {
            ContractPlot = new HashSet<ContractPlot>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int ProviderId { get; set; }
        public int BeneficiaryId { get; set; }
        public string DateOfConclusion { get; set; }
        public string DateOfExpiration { get; set; }

        public virtual Person Beneficiary { get; set; }
        public virtual Person Provider { get; set; }
        public virtual ICollection<ContractPlot> ContractPlot { get; set; }
    }
}