// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class ContractPlot
    {
        public int Id { get; set; }
        public int? ContractId { get; set; }
        public int? PlotId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Plot Plot { get; set; }
    }
}