// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class OrderStatus
    {
        public OrderStatus()
        {
            ChorePerson = new HashSet<ChorePerson>();
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ChorePerson> ChorePerson { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}