// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class Order
    {
        public int Id { get; set; }
        public double? AmountOfGoods { get; set; }
        public int CustomerId { get; set; }
        public int PlantId { get; set; }
        public int OrderStatusId { get; set; }

        public virtual Person Customer { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Plant Plant { get; set; }
    }
}