// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class Person
    {
        public Person()
        {
            ChorePerson = new HashSet<ChorePerson>();
            ContractBeneficiary = new HashSet<Contract>();
            ContractProvider = new HashSet<Contract>();
            Order = new HashSet<Order>();
            Plant = new HashSet<Plant>();
            Plot = new HashSet<Plot>();
        }

        public int Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public int? CityId { get; set; }
        public int? RoleId { get; set; }

        public virtual City City { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<ChorePerson> ChorePerson { get; set; }
        public virtual ICollection<Contract> ContractBeneficiary { get; set; }
        public virtual ICollection<Contract> ContractProvider { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Plant> Plant { get; set; }
        public virtual ICollection<Plot> Plot { get; set; }
    }
}