// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class Plant
    {
        public Plant()
        {
            IncomeAndExpenses = new HashSet<IncomeAndExpenses>();
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SubspeciesName { get; set; }
        public double? AmountOfGoods { get; set; }
        public double? Price { get; set; }
        public int? PlantTypeId { get; set; }
        public int? GoodsTypeId { get; set; }
        public int? ManufacturerId { get; set; }

        public virtual GoodsType GoodsType { get; set; }
        public virtual Person Manufacturer { get; set; }
        public virtual PlantType PlantType { get; set; }
        public virtual ICollection<IncomeAndExpenses> IncomeAndExpenses { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}