// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agriculture.Models
{
    public partial class Terrain
    {
        public Terrain()
        {
            Plot = new HashSet<Plot>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string SunPersence { get; set; }
        public int? GroundSlope { get; set; }

        public virtual ICollection<Plot> Plot { get; set; }
    }
}